"""Write exam3-homework-map-data.js from homework + review harvest JSON."""
from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
HOMEWORK_HARVEST = ROOT / "exam3-homework-harvest.json"
REVIEW_HARVEST = ROOT / "exam3-review-harvest.json"
OUT_PATH = ROOT / "exam3-homework-map-data.js"

SECTION_LABELS = {
    "3.8": "3.8 Implicit Differentiation",
    "3.11": "3.11 Related Rates",
    "4.1": "4.1 Maxima and Minima",
    "4.2": "4.2 Mean Value Theorem",
    "4.3": "4.3 What Derivatives Tell Us",
    "4.4": "4.4 Graphing Functions",
    "4.5": "4.5 Optimization Problems",
    "4.6": "4.6 Linear Approximation and Differentials",
    "4.7": "4.7 L'Hopital's Rule",
    "4.8": "4.8 Newton's Method",
}


def section_id(name: str) -> str:
    m = re.match(r"^(\d+\.\d+)", name)
    return m.group(1) if m else name.split()[0]


def qid_section(qid: str) -> str:
    m = re.match(r"^(\d+\.\d+)", qid)
    return m.group(1) if m else "other"


def problem_entry(p: dict) -> dict:
    out = {
        "summary": p.get("summary") or p.get("prompt") or "",
        "fullText": p.get("fullText") or p.get("prompt") or "",
    }
    if p.get("parts"):
        out["parts"] = p["parts"]
    if p.get("expr"):
        out["expr"] = p["expr"]
    if p.get("prompt") and p.get("prompt") != out["summary"]:
        out["prompt"] = p["prompt"]
    return out


def build_homework(sections: list) -> tuple[list, dict]:
    homework = []
    problems: dict[str, dict] = {}
    for entry in sections:
        if entry.get("error") or not entry.get("problems"):
            continue
        name = entry["requested"]
        sid = section_id(name)
        ids = [p["questionId"] for p in entry["problems"]]
        homework.append({"id": sid, "label": name, "section": sid, "ids": ids})
        for p in entry["problems"]:
            problems[p["questionId"]] = problem_entry(p)
    return homework, problems


def build_review(sections: list) -> tuple[list, dict]:
    review_sections: list[dict] = []
    review_problems: dict[str, dict] = {}
    current: dict | None = None

    for entry in sections:
        if entry.get("error") or not entry.get("problems"):
            continue
        for p in entry["problems"]:
            qid = p["questionId"]
            sid = qid_section(qid)
            if current is None or current["id"] != sid:
                current = {
                    "id": sid,
                    "label": SECTION_LABELS.get(sid, sid),
                    "section": sid,
                    "ids": [],
                }
                review_sections.append(current)
            current["ids"].append(qid)
            review_problems[qid] = problem_entry(p)

    return review_sections, review_problems


def main() -> None:
    homework_src = json.loads(HOMEWORK_HARVEST.read_text(encoding="utf-8"))
    homework, problems = build_homework(homework_src)

    review_sections: list = []
    review_problems: dict = {}
    if REVIEW_HARVEST.exists():
        review_src = json.loads(REVIEW_HARVEST.read_text(encoding="utf-8"))
        review_sections, review_problems = build_review(review_src)

    lines = [
        "// Exam 3 map data — Pearson print harvest (full problem text)",
        "// Generated by harvest/write_exam3_map_data.py",
        "const HOMEWORK = " + json.dumps(homework, indent=2) + ";",
        "",
        "const REVIEW = " + json.dumps(review_sections, indent=2) + ";",
        "",
        "const PROBLEMS = " + json.dumps(problems, indent=2) + ";",
        "",
        "const REVIEW_PROBLEMS = " + json.dumps(review_problems, indent=2) + ";",
    ]
    OUT_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(
        f"Wrote {OUT_PATH.name}: "
        f"{len(homework)} hw sections, {len(problems)} hw problems, "
        f"{len(review_sections)} review sections, {len(review_problems)} review problems"
    )


if __name__ == "__main__":
    main()
